export { defaultFormElements } from './default-form-elements'

export type { FormKitSchemaFormKit } from '@formkit/core'

export const fieldProps = [
  {
    name: 'text',
    tooltip: 'Allows user to enter text',
    icon: 'i-lucide-type',
    category: 'fields',
  },
  {
    name: 'email',
    tooltip: 'Allows user to enter email',
    icon: 'i-lucide-mail',
    category: 'fields',
  },
  {
    name: 'color',
    tooltip: 'Allows user to select color',
    icon: 'i-lucide-pipette',
    category: 'fields',
  },
  {
    name: 'number',
    tooltip: 'Allows user to enter number',
    icon: 'i-lucide-hash',
    category: 'fields',
  },
  {
    name: 'checkbox',
    tooltip: 'Allows user to select multiple options',
    icon: 'i-lucide-square-check',
    category: 'fields',
  },
  {
    name: 'date',
    tooltip: 'Allows user to select date',
    icon: 'i-lucide-calendar',
    category: 'fields',
  },
  {
    name: 'datetime-local',
    tooltip: 'Allows user to select date and time',
    icon: 'i-lucide-calendar-clock',
    category: 'fields',
  },
  {
    name: 'date-time',
    tooltip: 'Allows user to select date and time',
    icon: 'i-lucide-calendar-clock',
    category: 'fields',
  },
  {
    name: 'file',
    tooltip: 'Allows user to upload file',
    icon: 'i-lucide-paperclip',
    category: 'fields',
  },
  {
    name: 'password',
    tooltip: 'Allows user to enter password',
    icon: 'i-lucide-lock',
    category: 'fields',
  },
  {
    name: 'radio',
    tooltip: 'Allows user to select single option',
    icon: 'i-lucide-circle-dot',
    category: 'fields',
  },
  {
    name: 'range',
    tooltip: 'Allows user to select between a range of values',
    icon: 'i-lucide-sliders-horizontal',
    category: 'fields',
  },
  {
    name: 'select',
    tooltip: 'Allows user to select from a list of options',
    icon: 'i-lucide-list',
    category: 'fields',
  },
  {
    name: 'naiveCascader',
    tooltip: 'Allows user to select from a cascader',
    icon: 'i-lucide-list',
    category: 'fields',
  },
  {
    name: 'naiveTreeSelect',
    tooltip: 'Allows user to select from a tree',
    icon: 'i-lucide-list-tree',
    category: 'fields',
  },
  {
    name: 'naiveMention',
    tooltip: 'Allows user to mention options',
    icon: 'i-lucide-letter-text',
    category: 'fields',
  },
  {
    name: 'naiveRate',
    tooltip: 'Allows user to rate with stars',
    icon: 'i-lucide-sliders-horizontal',
    category: 'fields',
  },
  {
    name: 'naiveSwitch',
    tooltip: 'Allows user to toggle a boolean value',
    icon: 'i-lucide-square-check',
    category: 'fields',
  },
  {
    name: 'naiveCheckbox',
    tooltip: 'Allows user to toggle a checkbox value',
    icon: 'i-lucide-square-check',
    category: 'fields',
  },
  {
    name: 'naiveAvatar',
    tooltip: 'Avatar display',
    icon: 'i-stash:user-avatar',
    category: 'fields',
  },
  {
    name: 'naiveImage',
    tooltip: 'Image display',
    icon: 'i-lucide-image',
    category: 'fields',
  },
  {
    name: 'tel',
    tooltip: 'Allows user to enter telephone number',
    icon: 'i-lucide-phone',
    category: 'fields',
  },
  {
    name: 'textarea',
    tooltip: 'Allows user to enter multiple lines of text',
    icon: 'i-lucide-letter-text',
    category: 'fields',
  },
  {
    name: 'time',
    tooltip: 'Allows user to select time',
    icon: 'i-lucide-clock',
    category: 'fields',
  },
  {
    name: 'url',
    tooltip: 'Allows user to enter url',
    icon: 'i-lucide-link-2',
    category: 'fields',
  },
  {
    name: 'submit',
    tooltip: 'Allows user to submit form',
    icon: 'i-lucide-send-horizontal',
    category: 'static',
  },
  {
    name: 'naiveButton',
    tooltip: 'Naive UI button',
    icon: 'i-lucide-square-mouse-pointer',
    category: 'static',
  },
  {
    name: 'naiveText',
    tooltip: 'Typography text',
    icon: 'i-lucide-letter-text',
    category: 'static',
  },
  {
    name: 'naiveP',
    tooltip: 'Typography paragraph',
    icon: 'i-lucide-letter-text',
    category: 'static',
  },
  {
    name: 'naiveA',
    tooltip: 'Typography link',
    icon: 'i-lucide-link-2',
    category: 'static',
  },
  {
    name: 'naiveBlockquote',
    tooltip: 'Typography blockquote',
    icon: 'i-lucide-letter-text',
    category: 'static',
  },
  {
    name: 'naiveHr',
    tooltip: 'Typography divider',
    icon: 'i-lucide-sliders-horizontal',
    category: 'static',
  },
  {
    name: 'naiveH1',
    tooltip: 'Typography H1',
    icon: 'i-lucide-heading-1',
    category: 'static',
  },
  {
    name: 'naiveH2',
    tooltip: 'Typography H2',
    icon: 'i-lucide-heading-2',
    category: 'static',
  },
  {
    name: 'naiveH3',
    tooltip: 'Typography H3',
    icon: 'i-lucide-heading-3',
    category: 'static',
  },
  {
    name: 'naiveH4',
    tooltip: 'Typography H4',
    icon: 'i-lucide-heading-4',
    category: 'static',
  },
  {
    name: 'naiveH5',
    tooltip: 'Typography H5',
    icon: 'i-lucide-heading-5',
    category: 'static',
  },
  {
    name: 'naiveH6',
    tooltip: 'Typography H6',
    icon: 'i-lucide-heading-6',
    category: 'static',
  },
  {
    name: 'naiveUl',
    tooltip: 'Typography unordered list',
    icon: 'i-lucide-list',
    category: 'static',
  },
  {
    name: 'naiveOl',
    tooltip: 'Typography ordered list',
    icon: 'i-lucide-list',
    category: 'static',
  },
  {
    name: 'naiveLi',
    tooltip: 'Typography list item',
    icon: 'i-lucide-list',
    category: 'static',
  },
  {
    name: 'naiveDivider',
    tooltip: 'Naive UI divider',
    icon: 'i-lucide-sliders-horizontal',
    category: 'static',
  },
  {
    name: 'group',
    tooltip: 'Allows user to group fields together',
    icon: 'i-lucide-group',
    category: 'structure',
  },
  {
    name: 'list',
    tooltip: 'Allows user to group fields into an array',
    icon: 'i-lucide-list-tree',
    category: 'structure',
  },
]
